USE [2766_SalesMgmtRptg_Private]
GO

SELECT 
       [AMH_MarketCd]
      ,[AMH_MarketNm]
      ,[AMH_MarketUnitCd]
      ,[AMH_MarketUnitNm]
      ,[AMH_ClientGroupCd]
      ,[AMH_ClientGroupNm]
      ,[MRDRClientGroupCd]
      ,[TYPEOFWORKCD]
      ,[TypeOfWorkDesc]
      ,[ServiceDimensionCd]
      ,[ServiceDimensionNm]
      ,[ServiceGroupCd]
      ,[ServiceGroupShortNm]
      ,[MMS_SG]
      ,[ServiceGroupNm]
      ,[SubServiceGroupCd]
      ,[SubServiceGroupNm]
      ,[AMH_CountryCd]
      ,[CountryCd]
      ,[CountryNm]
      ,[CommercialFlag]
      ,[RateCardNm]
      ,[Career Level Code]
      ,[Career Level Description]
      ,[Career Level]
      ,[CurrencyCd]
      ,[CurrencyNm]
      ,[UOM]
  --    ,[Value]
      ,COUNT(*) as occurrences
  FROM [Targets].[ResourceLevelCatalogRates]
GROUP BY
       [AMH_MarketCd]
      ,[AMH_MarketNm]
      ,[AMH_MarketUnitCd]
      ,[AMH_MarketUnitNm]
      ,[AMH_ClientGroupCd]
      ,[AMH_ClientGroupNm]
      ,[MRDRClientGroupCd]
      ,[TYPEOFWORKCD]
      ,[TypeOfWorkDesc]
      ,[ServiceDimensionCd]
      ,[ServiceDimensionNm]
      ,[ServiceGroupCd]
      ,[ServiceGroupShortNm]
      ,[MMS_SG]
      ,[ServiceGroupNm]
      ,[SubServiceGroupCd]
      ,[SubServiceGroupNm]
      ,[AMH_CountryCd]
      ,[CountryCd]
      ,[CountryNm]
      ,[CommercialFlag]
      ,[RateCardNm]
      ,[Career Level Code]
      ,[Career Level Description]
      ,[Career Level]
      ,[CurrencyCd]
      ,[CurrencyNm]
      ,[UOM]
--      ,[Value]
HAVING 
    COUNT(*) > 1;
